force-app/main/default/objects/Account/fields/LXD_N_Distribuidor__c.field-meta.xml
<CustomField>
    <fullName>LXD_N_Distribuidor__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Número de distribuidor</inlineHelpText>
    <label>Nº Distribuidor</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MX_SKY_ColoiaEnv__c.field-meta.xml
<CustomField>
    <fullName>MX_SKY_ColoiaEnv__c</fullName>
    <label>Colonia</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MX_SKY_EntrecalIeEnvDos__c.field-meta.xml
<CustomField>
    <fullName>MX_SKY_EntrecalIeEnvDos__c</fullName>
    <label>Entre calle 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MX_SKY_EntrecalleUnoEnv__c.field-meta.xml
<CustomField>
    <fullName>MX_SKY_EntrecalleUnoEnv__c</fullName>
    <label>Entre calle 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MX_SKY_NumExtEnv__c.field-meta.xml
<CustomField>
    <fullName>MX_SKY_NumExtEnv__c</fullName>
    <label>Número exterior envío</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MX_SKY_NumIntEnv__c.field-meta.xml
<CustomField>
    <fullName>MX_SKY_NumIntEnv__c</fullName>
    <label>Número interior</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Atributos__c.field-meta.xml
<CustomField>
    <fullName>LXD_Atributos__c</fullName>
    <inlineHelpText>Atributos de la clave operativa</inlineHelpText>
    <label>Atributos</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Banderas__c.field-meta.xml
<CustomField>
    <fullName>LXD_Banderas__c</fullName>
    <inlineHelpText>Programas de capacitación del técnico, vendedor, .....</inlineHelpText>
    <label>Banderas</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Clave_operativa__c.field-meta.xml
<CustomField>
    <fullName>LXD_Clave_operativa__c</fullName>
    <inlineHelpText>Clave operativa</inlineHelpText>
    <label>Clave operativa</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Contrasena_personal__c.field-meta.xml
<CustomField>
    <fullName>LXD_Contrasena_personal__c</fullName>
    <label>Contraseña personal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Dato_secreto__c.field-meta.xml
<CustomField>
    <fullName>LXD_Dato_secreto__c</fullName>
    <inlineHelpText>Dato secreto del Técnico, Vendedor, .....</inlineHelpText>
    <label>Dato secreto</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Estado_civil__c.field-meta.xml
<CustomField>
    <fullName>LXD_Estado_civil__c</fullName>
    <inlineHelpText>Estado civil del Técnico, Vendedor, .....</inlineHelpText>
    <label>Estado civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casado</fullName>
            </value>
            <value>
                <fullName>Soltero</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Estatus_de_la_clave_operativa__c.field-meta.xml
<CustomField>
    <fullName>LXD_Estatus_de_la_clave_operativa__c</fullName>
    <inlineHelpText>Estatus de la clave operativa</inlineHelpText>
    <label>Estatus de la clave operativa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Baja Temporal</fullName>
            </value>
            <value>
                <fullName>Boletinado</fullName>
            </value>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Estatus_de_la_relacion__c.field-meta.xml
<CustomField>
    <fullName>LXD_Estatus_de_la_relacion__c</fullName>
    <inlineHelpText>Estatus de la relación</inlineHelpText>
    <label>Estatus de la relación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Baja logica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Fecha_alta__c.field-meta.xml
<CustomField>
    <fullName>LXD_Fecha_alta__c</fullName>
    <inlineHelpText>Fecha de alta</inlineHelpText>
    <label>Fecha alta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Genero__c.field-meta.xml
<CustomField>
    <fullName>LXD_Genero__c</fullName>
    <inlineHelpText>Género del Técnico, Vendedor, .....</inlineHelpText>
    <label>Genero</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>LXD_Nacionalidad__c</fullName>
    <inlineHelpText>Nacionalidad del Técnico, Vendedor, .....</inlineHelpText>
    <label>Nacionalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COLOMBIANA</fullName>
            </value>
            <value>
                <fullName>COSTARRICENSE</fullName>
            </value>
            <value>
                <fullName>CUBANO</fullName>
            </value>
            <value>
                <fullName>GUATEMALTECA</fullName>
            </value>
            <value>
                <fullName>HONDUREÑA</fullName>
            </value>
            <value>
                <fullName>MEXICANA</fullName>
            </value>
            <value>
                <fullName>NICARAGUENSE</fullName>
            </value>
            <value>
                <fullName>PANAMEÑA</fullName>
            </value>
            <value>
                <fullName>SALVADOREÑA</fullName>
            </value>
            <value>
                <fullName>VENEZOLANA</fullName>
            </value>
            <value>
                <fullName>DOMINICANA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Nivel_de_estudios__c.field-meta.xml
<CustomField>
    <fullName>LXD_Nivel_de_estudios__c</fullName>
    <label>Nivel de estudios</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LXD_Nivel_de_estudios</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Notas_1__c.field-meta.xml
<CustomField>
    <fullName>LXD_Notas_1__c</fullName>
    <inlineHelpText>Notas acerca del Técnico, Vendedor, .....</inlineHelpText>
    <label>Notas 1</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Notas_2__c.field-meta.xml
<CustomField>
    <fullName>LXD_Notas_2__c</fullName>
    <inlineHelpText>Notas acerca del Técnico, Vendedor, .....</inlineHelpText>
    <label>Notas 2</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Numero_ID__c.field-meta.xml
<CustomField>
    <fullName>LXD_Numero_ID__c</fullName>
    <inlineHelpText>Número de identificación del Técnico, Vendedor, ....</inlineHelpText>
    <label>Numero ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Tipo_de_clave_operativa__c.field-meta.xml
<CustomField>
    <fullName>LXD_Tipo_de_clave_operativa__c</fullName>
    <label>Tipo de clave operativa</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LXD_Tipo_de_clave_operativa</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MX_SKY_MuniAlca__c.field-meta.xml
<CustomField>
    <fullName>MX_SKY_MuniAlca__c</fullName>
    <label>Municipio / Alcaldia</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LXD_ContactTriggerTest.cls
@isTest
public with sharing class LXD_ContactTriggerTest {
    public static Account cuenta;
    public static Contact contacto;
    public static string resultMessage;
    static{
        resultMessage = '';
        cuenta = new Account (
            LXD_N_Distribuidor__c = 'DI111111',
            Name='Test'
        );
        insert cuenta;
        contacto = new Contact(
            LastName = 'test',
            FirstName = 'test',
            MiddleName = 'test',
            Suffix = 'test',
            Phone = '111111111',
            MobilePhone = '11111111',
            Email = 'test@test.com',
            LXD_Clave_operativa__c = 'TT00001',
            LXD_Estatus_de_la_clave_operativa__c = 'Activo',
            LXD_Tipo_de_clave_operativa__c = 'Pre-Técnico',
            AccountId = cuenta.Id,
            MailingPostalCode = '2158',
            MailingCity = 'Buenos Aires',
            Title = 'Tecnico',
            LXD_Nivel_de_estudios__c = 'Carrera técnica',
            MX_SKY_NumExtEnv__c = '12',
            MX_SKY_NumIntEnv__c = '12',
            MX_SKY_ColoiaEnv__c = 'test',
            MX_SKY_MuniAlca__c = 'test',
            MX_SKY_EntrecalleUnoEnv__c = 'test',
            MX_SKY_EntrecalIeEnvDos__c = 'test',
            LXD_Estatus_de_la_relacion__c = 'Activo',
            LXD_Atributos__c = 'test',
            LXD_Banderas__c = 'test',
            MailingCountry = 'Mexico',
            LXD_Fecha_alta__c = date.newInstance(1987, 12, 17),
            LXD_Genero__c = 'Masculino',
            LXD_Nacionalidad__c = 'MEXICANA',
            LXD_Estado_civil__c = 'Soltero',
            LXD_Numero_ID__c = '11111111',
            LXD_Dato_secreto__c = 'test',
            LXD_Notas_1__c = 'test',
            LXD_Notas_2__c = 'test',
            LXD_Contrasena_personal__c = 'test'
        );
        insert contacto;
    }
    @IsTest
    static void ShouldCallJohnnyRocketWithSuccessMessage(){
        
        SingleRequestMock mock = new SingleRequestMock(
            200,
            'Complete',
            '{Messagge: Success}',
            null
        );
        Test.setMock(HttpCalloutMock.class, mock);
        contacto.LXD_Tipo_de_clave_operativa__c = 'Técnico';
        resultMessage = '';
        try{
            Test.startTest();
                update contacto;
            Test.stopTest();
        } catch (DmlException ex) {
            system.debug('Envio de Claves Operativas a Jhonny Rocket'+ ex.getMessage());
            resultMessage = ex.getMessage();
        }  
        System.assertEquals('Envio de Claves Operativas a Jhonny Rocket', resultMessage);
    }


    @IsTest
    static void ShouldCallJohnnyRocketWithErrorMessage(){
        SingleRequestMock mock = new SingleRequestMock(
            400,
            'Error',
            '{Messagge: Error}',
            null
        );
        Test.setMock(HttpCalloutMock.class, mock);
        contacto.LXD_Tipo_de_clave_operativa__c = 'Técnico';
        resultMessage = '';
        try{
            Test.startTest();
                update contacto;
            Test.stopTest();
        } catch (DmlException ex) {
            system.debug('No se pudo crear el contacto'+ ex.getMessage());
            resultMessage = ex.getMessage();
        }  
        System.assertEquals('No se pudo crear el contacto', resultMessage);
    }
}