force-app/main/default/objects/Account/fields/LXD_N_Distribuidor__c.field-meta.xml
<CustomField>
    <fullName>LXD_N_Distribuidor__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Número de distribuidor</inlineHelpText>
    <label>Nº Distribuidor</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Atributos__c.field-meta.xml
<CustomField>
    <fullName>LXD_Atributos__c</fullName>
    <inlineHelpText>Atributos de la clave operativa</inlineHelpText>
    <label>Atributos</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Banderas__c.field-meta.xml
<CustomField>
    <fullName>LXD_Banderas__c</fullName>
    <inlineHelpText>Programas de capacitación del técnico, vendedor, .....</inlineHelpText>
    <label>Banderas</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Clave_o_Numero__c.field-meta.xml
<CustomField>
    <fullName>LXD_Clave_o_Numero__c</fullName>
    <label>Clave o Número</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Clave_operativa__c.field-meta.xml
<CustomField>
    <fullName>LXD_Clave_operativa__c</fullName>
    <inlineHelpText>Clave operativa</inlineHelpText>
    <label>Clave operativa</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Contrasena_personal__c.field-meta.xml
<CustomField>
    <fullName>LXD_Contrasena_personal__c</fullName>
    <label>Contraseña personal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Dato_secreto__c.field-meta.xml
<CustomField>
    <fullName>LXD_Dato_secreto__c</fullName>
    <inlineHelpText>Dato secreto del Técnico, Vendedor, .....</inlineHelpText>
    <label>Dato secreto</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Estado_civil__c.field-meta.xml
<CustomField>
    <fullName>LXD_Estado_civil__c</fullName>
    <inlineHelpText>Estado civil del Técnico, Vendedor, .....</inlineHelpText>
    <label>Estado civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casado</fullName>
            </value>
            <value>
                <fullName>Soltero</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Estatus_de_la_clave_operativa__c.field-meta.xml
<CustomField>
    <fullName>LXD_Estatus_de_la_clave_operativa__c</fullName>
    <inlineHelpText>Estatus de la clave operativa</inlineHelpText>
    <label>Estatus de la clave operativa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Baja Temporal</fullName>
            </value>
            <value>
                <fullName>Boletinado</fullName>
            </value>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Estatus_de_la_relacion__c.field-meta.xml
<CustomField>
    <fullName>LXD_Estatus_de_la_relacion__c</fullName>
    <inlineHelpText>Estatus de la relación</inlineHelpText>
    <label>Estatus de la relación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Baja logica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Fecha_alta__c.field-meta.xml
<CustomField>
    <fullName>LXD_Fecha_alta__c</fullName>
    <inlineHelpText>Fecha de alta</inlineHelpText>
    <label>Fecha alta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Genero__c.field-meta.xml
<CustomField>
    <fullName>LXD_Genero__c</fullName>
    <inlineHelpText>Género del Técnico, Vendedor, .....</inlineHelpText>
    <label>Genero</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Identificacion_Personal__c.field-meta.xml
<CustomField>
    <fullName>LXD_Identificacion_Personal__c</fullName>
    <label>Identificación Personal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LXD_Identificacion_Personal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>LXD_Nacionalidad__c</fullName>
    <inlineHelpText>Nacionalidad del Técnico, Vendedor, .....</inlineHelpText>
    <label>Nacionalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COLOMBIANA</fullName>
            </value>
            <value>
                <fullName>COSTARRICENSE</fullName>
            </value>
            <value>
                <fullName>CUBANO</fullName>
            </value>
            <value>
                <fullName>GUATEMALTECA</fullName>
            </value>
            <value>
                <fullName>HONDUREÑA</fullName>
            </value>
            <value>
                <fullName>MEXICANA</fullName>
            </value>
            <value>
                <fullName>NICARAGUENSE</fullName>
            </value>
            <value>
                <fullName>PANAMEÑA</fullName>
            </value>
            <value>
                <fullName>SALVADOREÑA</fullName>
            </value>
            <value>
                <fullName>VENEZOLANA</fullName>
            </value>
            <value>
                <fullName>DOMINICANA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Notas_1__c.field-meta.xml
<CustomField>
    <fullName>LXD_Notas_1__c</fullName>
    <inlineHelpText>Notas acerca del Técnico, Vendedor, .....</inlineHelpText>
    <label>Notas 1</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Notas_2__c.field-meta.xml
<CustomField>
    <fullName>LXD_Notas_2__c</fullName>
    <inlineHelpText>Notas acerca del Técnico, Vendedor, .....</inlineHelpText>
    <label>Notas 2</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Numero_ID__c.field-meta.xml
<CustomField>
    <fullName>LXD_Numero_ID__c</fullName>
    <inlineHelpText>Número de identificación del Técnico, Vendedor, ....</inlineHelpText>
    <label>Numero ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Telefono_Celular__c.field-meta.xml
<CustomField>
    <fullName>LXD_Telefono_Celular__c</fullName>
    <label>Télefono Celular</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Tipo_ID__c.field-meta.xml
<CustomField>
    <fullName>LXD_Tipo_ID__c</fullName>
    <inlineHelpText>Tipo de identificación Técnico, Vendedor, .....</inlineHelpText>
    <label>Tipo ID</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credencial para votar (INE)</fullName>
            </value>
            <value>
                <fullName>Licencia para conducir</fullName>
            </value>
            <value>
                <fullName>Pasaporte</fullName>
            </value>
            <value>
                <fullName>Cartilla Militar</fullName>
            </value>
            <value>
                <fullName>Credencial IMSS</fullName>
            </value>
            <value>
                <fullName>Excepción</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LXD_RESTClaveOperativaManager.cls
@RestResource(urlMapping='/Contact/*')
global class LXD_RESTClaveOperativaManager {
    
    @HttpGet
    global static Map<String, String> LXD_RequestClaveOperativa() {
        Map<String, String> msg200;
        Map<String, String> msg404 = new Map<String, String>{'Message' => 'Contact not found', 'Code' => '404'}; 
        Map<String, String> msg400;
        Map<String, String> idResult;
        Map<String, Object> acctMap = new Map<String, Object>();
        String[] fields = new String[]{'LastName','FirstName','MiddleName','Suffix','MailingCountry',
                                        'Phone','MobilePhone','Email','LXD_Clave_operativa__c',
                                        'LXD_Estatus_de_la_clave_operativa__c','LXD_Estatus_de_la_relacion__c',
                                        'LXD_Atributos__c','LXD_Banderas__c','LXD_Fecha_alta__c','LXD_Genero__c',
                                        'LXD_Nacionalidad__c','LXD_Estado_civil__c','LXD_Tipo_ID__c',
                                        'LXD_Numero_ID__c','LXD_Dato_secreto__c','LXD_Notas_1__c',
                                        'LXD_Notas_2__c','LXD_Contrasena_personal__c','LXD_Clave_o_Numero__c',
                                        'LXD_Identificacion_Personal__c','LXD_Telefono_Celular__c'};
                                        
        System.debug(fields);
        try {
            RestRequest request = RestContext.request;
            String claveOperativa = request.params.get('ClaveOperativa');
            String pais = request.params.get('Pais');
            if(claveOperativa == null || pais == null) throw new DMLException('Por favor asegurese de pasar todos los parametros');
            List<Contact> thisContact = Database.query(
                'SELECT ' + String.join(fields,',') 
                +' FROM Contact'+
                ' WHERE LXD_Clave_operativa__c LIKE :claveOperativa'+
                ' AND MailingCountry LIKE :pais'+
                ' LIMIT 1');
            System.debug('Contactos '+thisContact);
            if (!thisContact.isEmpty()) {
                acctMap = thisContact[0].getPopulatedFieldsAsMap();
                for (String field : fields){
                    if (!acctMap.containsKey(field)){
                        system.debug('cammpo '+field);
                        if(field == 'LXD_Fecha_alta__c'){
                            thisContact[0].put(field,null);
                        }else{
                            thisContact[0].put(field,'');
                        }
                        
                    }                              
                }
                System.debug('map = '+ thisContact[0]);
                idResult = new Map<String, String>{'Message' => String.valueOf(thisContact[0]), 'Code' => '200'};
            }else{
                idResult = msg404;
            }
            return idResult;   
        }  
        catch(Exception e) {
            System.debug(e);
            return msg400= new Map<String, String>{'Message' => 'Bad Request Error', 'Code' => '400', 'Detail' => e.getMessage()};
        }
    }

    @HttpPost
    global static Map<String, String> LXD_UpdateClaveOperativa() {
        Map<String, String> msg200 = new Map<String, String>{'Message' => 'Contact Updated', 'Code' => '200'}; 
        Map<String, String> msg404;
        Map<String, String> msg500 ;
        Map<String, String> msg400 = new Map<String, String>{'Message' => 'Bad Request Error', 'Code' => '400'};
        Map<String, String> idResult;
        try {
            RestRequest request = RestContext.request;
            Map<String, Object> params = (Map<String, Object>)JSON.deserializeUntyped(request.requestbody.tostring());
            
            String LXD_ClaveOperativa = (String)params.get('ClaveOperativa');
            String pais = (String)params.get('Pais');
            
            if(LXD_ClaveOperativa== null || pais == null) {
                throw new DMLException('Por favor asegurese de pasar todos los parametros');
            }
            
            List<Contact> thisContact = [
                SELECT 
                Id, LastName,FirstName,MiddleName,Suffix,Phone,MobilePhone,
                Email,LXD_Clave_operativa__c,LXD_Estatus_de_la_clave_operativa__c,
                LXD_Estatus_de_la_relacion__c,LXD_Atributos__c,LXD_Banderas__c,
                LXD_Fecha_alta__c,LXD_Genero__c,LXD_Nacionalidad__c,LXD_Estado_civil__c,
                LXD_Identificacion_Personal__c,LXD_Numero_ID__c,LXD_Dato_secreto__c,LXD_Notas_1__c,
                LXD_Notas_2__c,LXD_Clave_o_Numero__c,LXD_Telefono_Celular__c,LXD_Contrasena_personal__c
                FROM Contact 
                WHERE LXD_Clave_operativa__c = :LXD_ClaveOperativa 
                AND MailingCountry = :pais
                LIMIT 1
            ]; 
            
            if (!thisContact.isEmpty()) {

                thisContact[0].LastName = (String)params.get('LastName')== 'null' ? '.' : (String)params.get('LastName');
                thisContact[0].FirstName = (String)params.get('FirstName');
                thisContact[0].MiddleName = (String)params.get('MiddleName')== 'null' ? null : (String)params.get('MiddleName');
                thisContact[0].Suffix = (String)params.get('Suffix') == 'null' ? null : (String)params.get('Suffix');
                thisContact[0].Phone = (String)params.get('Phone')== 'null' ? null : (String)params.get('Phone');
                thisContact[0].LXD_Telefono_Celular__c = (String)params.get('MobilePhone');
                thisContact[0].Email = (String)params.get('Email')== 'null' ? null : (String)params.get('Email');
                thisContact[0].LXD_Estatus_de_la_clave_operativa__c = (String)params.get('LXD_Estatus_de_la_clave_operativa__c');
                thisContact[0].LXD_Estatus_de_la_relacion__c = (String)params.get('LXD_Estatus_de_la_relacion__c');
                thisContact[0].LXD_Atributos__c = (String)params.get('LXD_Atributos__c');
                thisContact[0].LXD_Banderas__c = (String)params.get('LXD_Banderas__c');
                thisContact[0].LXD_Genero__c = (String)params.get('LXD_Genero__c');
                thisContact[0].LXD_Nacionalidad__c = (String)params.get('LXD_Nacionalidad__c');
                thisContact[0].LXD_Estado_civil__c = (String)params.get('LXD_Estado_civil__c');
                thisContact[0].LXD_Identificacion_Personal__c = (String)params.get('LXD_Tipo_ID__c');
                thisContact[0].LXD_Clave_o_Numero__c = (String)params.get('LXD_Numero_ID__c');
                thisContact[0].LXD_Dato_secreto__c = (String)params.get('LXD_Dato_secreto__c');
                thisContact[0].LXD_Notas_1__c = (String)params.get('LXD_Notas_1__c')== 'null' ? null : (String)params.get('LXD_Notas_1__c');
                thisContact[0].LXD_Notas_2__c = (String)params.get('LXD_Notas_2__c')== 'null' ? null : (String)params.get('LXD_Notas_2__c');
                thisContact[0].LXD_Contrasena_personal__c = (String)params.get('LXD_Contrasena_personal__c');
                thisContact[0].MailingCountry = (String)params.get('Pais');

                update thisContact[0];                  
                idResult =  msg200; 
            }else{
                idResult = new Map<String, String>{
                    'Message' => 'Policy not found',
                    'Code' => '404', 
                    'Detail'=> 'La combinacion de clave: '+LXD_ClaveOperativa+' y el pais: '+pais+' no fue encontrado en la base de datos'
                };
            }

            String nDistribuidor = (String)params.get('LXD_N_Distribuidor__c');
            String statusRelacion = (String)params.get('LXD_Estatus_de_la_relacion__c');
            system.debug('nDistribuidor '+nDistribuidor);
            system.debug('statusRelacion '+statusRelacion);

            List<Account> accList = [
                SELECT Id, LXD_N_Distribuidor__c 
                    FROM Account 
                    WHERE LXD_N_Distribuidor__c = :nDistribuidor 
                    LIMIT 1
            ];
            system.debug('accList '+accList);

            if (!accList.isEmpty()) {
                List<AccountContactRelation> accConRelList = [
                    SELECT Id, AccountId, ContactId, IsActive 
                        FROM AccountContactRelation 
                        WHERE AccountId = :accList[0].Id
                    		AND ContactId = :thisContact[0].Id
                ];
                
                system.debug('accConRelList '+accConRelList);

                if (!accConRelList.isEmpty()) {
                    if (statusRelacion == 'Activo') {
                        accConRelList[0].IsActive = True;
                    } else if (statusRelacion == 'Baja logica') {
                        accConRelList[0].IsActive = False;
                    }
                    system.debug('accConRelList2 '+accConRelList);
                    update accConRelList;
                } else {
                    AccountContactRelation newAccConRelation = new AccountContactRelation();
                    newAccConRelation.AccountId = accList[0].Id;
                    newAccConRelation.ContactId = thisContact[0].Id;
                    newAccConRelation.IsActive = True;
                    
                    if (statusRelacion == 'Baja logica') {
                        newAccConRelation.IsActive = False;
                    }
                    system.debug('newAccConRelation '+newAccConRelation);
                    insert newAccConRelation;                
                }
            }
            system.debug('idResult '+idResult);
            return idResult;     
        }catch(Exception e) {
            return msg400 = new Map<String, String>{'Message' => 'Bad Request Error', 'Code' => '400', 'Detail'=>e.getMessage()}; 
        }
    }
}