force-app/main/default/objects/Account/fields/LXD_Estatus__c.field-meta.xml
<CustomField>
    <fullName>LXD_Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activa</fullName>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LXD_N_Distribuidor__c.field-meta.xml
<CustomField>
    <fullName>LXD_N_Distribuidor__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Número de distribuidor</inlineHelpText>
    <label>Nº Distribuidor</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Atributos__c.field-meta.xml
<CustomField>
    <fullName>LXD_Atributos__c</fullName>
    <inlineHelpText>Atributos de la clave operativa</inlineHelpText>
    <label>Atributos</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Banderas__c.field-meta.xml
<CustomField>
    <fullName>LXD_Banderas__c</fullName>
    <inlineHelpText>Programas de capacitación del técnico, vendedor, .....</inlineHelpText>
    <label>Banderas</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Clave_o_Numero__c.field-meta.xml
<CustomField>
    <fullName>LXD_Clave_o_Numero__c</fullName>
    <label>Clave o Número</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Clave_operativa__c.field-meta.xml
<CustomField>
    <fullName>LXD_Clave_operativa__c</fullName>
    <inlineHelpText>Clave operativa</inlineHelpText>
    <label>Clave operativa</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Contrasena_personal__c.field-meta.xml
<CustomField>
    <fullName>LXD_Contrasena_personal__c</fullName>
    <label>Contraseña personal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Dato_secreto__c.field-meta.xml
<CustomField>
    <fullName>LXD_Dato_secreto__c</fullName>
    <inlineHelpText>Dato secreto del Técnico, Vendedor, .....</inlineHelpText>
    <label>Dato secreto</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Estado_civil__c.field-meta.xml
<CustomField>
    <fullName>LXD_Estado_civil__c</fullName>
    <inlineHelpText>Estado civil del Técnico, Vendedor, .....</inlineHelpText>
    <label>Estado civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casado</fullName>
            </value>
            <value>
                <fullName>Soltero</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Estatus_de_la_clave_operativa__c.field-meta.xml
<CustomField>
    <fullName>LXD_Estatus_de_la_clave_operativa__c</fullName>
    <inlineHelpText>Estatus de la clave operativa</inlineHelpText>
    <label>Estatus de la clave operativa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Baja Temporal</fullName>
            </value>
            <value>
                <fullName>Boletinado</fullName>
            </value>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Estatus_de_la_relacion__c.field-meta.xml
<CustomField>
    <fullName>LXD_Estatus_de_la_relacion__c</fullName>
    <inlineHelpText>Estatus de la relación</inlineHelpText>
    <label>Estatus de la relación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Baja logica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Fecha_alta__c.field-meta.xml
<CustomField>
    <fullName>LXD_Fecha_alta__c</fullName>
    <inlineHelpText>Fecha de alta</inlineHelpText>
    <label>Fecha alta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Genero__c.field-meta.xml
<CustomField>
    <fullName>LXD_Genero__c</fullName>
    <inlineHelpText>Género del Técnico, Vendedor, .....</inlineHelpText>
    <label>Genero</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Identificacion_Personal__c.field-meta.xml
<CustomField>
    <fullName>LXD_Identificacion_Personal__c</fullName>
    <label>Identificación Personal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LXD_Identificacion_Personal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>LXD_Nacionalidad__c</fullName>
    <inlineHelpText>Nacionalidad del Técnico, Vendedor, .....</inlineHelpText>
    <label>Nacionalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COLOMBIANA</fullName>
            </value>
            <value>
                <fullName>COSTARRICENSE</fullName>
            </value>
            <value>
                <fullName>CUBANO</fullName>
            </value>
            <value>
                <fullName>GUATEMALTECA</fullName>
            </value>
            <value>
                <fullName>HONDUREÑA</fullName>
            </value>
            <value>
                <fullName>MEXICANA</fullName>
            </value>
            <value>
                <fullName>NICARAGUENSE</fullName>
            </value>
            <value>
                <fullName>PANAMEÑA</fullName>
            </value>
            <value>
                <fullName>SALVADOREÑA</fullName>
            </value>
            <value>
                <fullName>VENEZOLANA</fullName>
            </value>
            <value>
                <fullName>DOMINICANA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Notas_1__c.field-meta.xml
<CustomField>
    <fullName>LXD_Notas_1__c</fullName>
    <inlineHelpText>Notas acerca del Técnico, Vendedor, .....</inlineHelpText>
    <label>Notas 1</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Notas_2__c.field-meta.xml
<CustomField>
    <fullName>LXD_Notas_2__c</fullName>
    <inlineHelpText>Notas acerca del Técnico, Vendedor, .....</inlineHelpText>
    <label>Notas 2</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Numero_ID__c.field-meta.xml
<CustomField>
    <fullName>LXD_Numero_ID__c</fullName>
    <inlineHelpText>Número de identificación del Técnico, Vendedor, ....</inlineHelpText>
    <label>Numero ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Telefono_Celular__c.field-meta.xml
<CustomField>
    <fullName>LXD_Telefono_Celular__c</fullName>
    <label>Télefono Celular</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Tipo_ID__c.field-meta.xml
<CustomField>
    <fullName>LXD_Tipo_ID__c</fullName>
    <inlineHelpText>Tipo de identificación Técnico, Vendedor, .....</inlineHelpText>
    <label>Tipo ID</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credencial para votar (INE)</fullName>
            </value>
            <value>
                <fullName>Licencia para conducir</fullName>
            </value>
            <value>
                <fullName>Pasaporte</fullName>
            </value>
            <value>
                <fullName>Cartilla Militar</fullName>
            </value>
            <value>
                <fullName>Credencial IMSS</fullName>
            </value>
            <value>
                <fullName>Excepción</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LXD_RESTClaveOperativaManagerTest.cls
@IsTest
private class LXD_RESTClaveOperativaManagerTest {
    
    @isTest static void RequestShouldReturnResponse200() { //Test positivo
        String contactId = createTestRecord();  //crea un object Asset para Test
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Contact/';
        request.httpMethod = 'Get';
        request.addHeader('Content-Type', 'application/json');
        request.addParameter('ClaveOperativa', 'MN00001');
        request.addParameter('Pais', 'Mexico');
        RestContext.request = request;    
        Map<String, String> svResult = LXD_RESTClaveOperativaManager.LXD_RequestClaveOperativa();  // Actualiza el Asset Test
        Map<String,String> expextedResult = new Map<String, String>{
            'Message' => 'Contact:{LastName=Noy, FirstName=Martin, MailingCountry=Mexico, LXD_Clave_operativa__c=MN00001, Id='+contactId+', MiddleName=, Suffix=, Phone=, MobilePhone=, Email=, LXD_Estatus_de_la_clave_operativa__c=, LXD_Estatus_de_la_relacion__c=, LXD_Atributos__c=, LXD_Banderas__c=, LXD_Fecha_alta__c=null, LXD_Genero__c=, LXD_Nacionalidad__c=, LXD_Estado_civil__c=, LXD_Tipo_ID__c=, LXD_Numero_ID__c=, LXD_Dato_secreto__c=, LXD_Notas_1__c=, LXD_Notas_2__c=, LXD_Contrasena_personal__c=, LXD_Clave_o_Numero__c=, LXD_Identificacion_Personal__c=, LXD_Telefono_Celular__c=}', 
            'Code' => '200'
        };
        System.assertEquals(expextedResult, svResult);
    } 
    
    @isTest static void RequestShouldReturnResponse404() { //Test negativo
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Contact/';
        request.httpMethod = 'Get';
        request.addHeader('Content-Type', 'application/json');
        request.addParameter('ClaveOperativa', 'MN00001');
        request.addParameter('Pais', 'Mexico');
        RestContext.request = request;    
        Map<String, String> svResult = LXD_RESTClaveOperativaManager.LXD_RequestClaveOperativa();  // Actualiza el Asset Test
        Map<String,String> expextedResult = new Map<String, String>{
            'Message' => 'Contact not found', 
            'Code' => '404'
        };
        System.assertEquals(expextedResult, svResult);
    } 

    @isTest static void RequestShouldReturnResponse400() { //Test exception
        String contactId = createTestRecord();  //crea un object Asset para Test
        Map<String,String> params =new Map<String,String>{'ClaveOperativa'=>'MN00001','Pais'=>'Mexico'};
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Contact/';
        request.httpMethod = 'Get';
        request.addHeader('Content-Type', 'application/json');
        request.addParameter('ClaveOperativa', 'MN00001');
        RestContext.request = request;    
        Map<String, String> svResult = LXD_RESTClaveOperativaManager.LXD_RequestClaveOperativa();  // Actualiza el Asset Test
        Map<String,String> expextedResult = new Map<String, String>{
            'Message' => 'Bad Request Error', 
            'Code' => '400',
            'Detail' => 'Por favor asegurese de pasar todos los parametros'
        };
        System.assertEquals(expextedResult, svResult);
    }       
    
    // Metodos test del update
    @isTest static void UpadteShouldReturnResponse200() { //Test positivo
        String contactId = createTestRecord();  //crea un object Asset para Test
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Contact/';
        request.httpMethod = 'Post';
        request.addHeader('Content-Type', 'application/json');

        RestContext.request = request;
        request.requestBody = Blob.valueOf('{'+
        '"ClaveOperativa": "MN00001",'+
        '"Pais": "Mexico",'+
        '"LastName": ".",'+
        '"FirstName": "Florencia",'+
        '"MiddleName": null,'+
        '"Suffix": "apellido2",'+
        '"Phone": "54911218029 44",'+
        '"MobilePhone": null,'+
        '"Email": "fviacava@labsxd.com",'+
        '"LXD_Clave_operativa__c": "MN00001",'+
        '"LXD_Estatus_de_la_clave_operativa__c": "Activo",'+
        '"LXD_Estatus_de_la_relacion__c": "Activo",'+
        '"LXD_Atributos__c": null,'+
        '"LXD_Banderas__c": null,'+
        '"LXD_Genero__c": "Masculino",'+
        '"LXD_Nacionalidad__c": "MEXICANA",'+
        '"LXD_Estado_civil__c": "Soltero",'+
        '"LXD_Tipo_ID__c": "PASAPORTE",'+
        '"LXD_Numero_ID__c": "2143",'+
        '"LXD_Dato_secreto__c": "asd",'+
        '"LXD_Notas_1__c": null,'+
        '"LXD_Notas_2__c": null,'+
        '"LXD_Contrasena_personal__c": "abc",'+
        '"MailingCountry": "Mexico"'+
        '}');
        RestContext.request = request;    
        Map<String, String> svResult = LXD_RESTClaveOperativaManager.LXD_UpdateClaveOperativa();  // Actualiza el Asset Test
        Map<String,String> expextedResult = new Map<String, String>{
            'Message' => 'Contact Updated', 
            'Code' => '200'
        };
        System.assertEquals(expextedResult, svResult);
    } 
    
    @isTest static void UpadteShouldReturnResponse404() { //Test negativo
         RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Contact/';
        request.httpMethod = 'Post';
        
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf('{'+
        '"ClaveOperativa": "MN00001",'+
        '"Pais": "Mexico",'+
        '"LastName": ".",'+
        '"FirstName": "Florencia",'+
        '"MiddleName": null,'+
        '"Suffix": "apellido2",'+
        '"Phone": "54911218029 44",'+
        '"MobilePhone": null,'+
        '"Email": "fviacava@labsxd.com",'+
        '"LXD_Clave_operativa__c": "MN00002",'+
        '"LXD_Estatus_de_la_clave_operativa__c": "Activo",'+
        '"LXD_Estatus_de_la_relacion__c": "Activo",'+
        '"LXD_Atributos__c": null,'+
        '"LXD_Banderas__c": null,'+
        '"LXD_Genero__c": "Masculino",'+
        '"LXD_Nacionalidad__c": "MEXICANA",'+
        '"LXD_Estado_civil__c": "Soltero",'+
        '"LXD_Tipo_ID__c": "PASAPORTE",'+
        '"LXD_Numero_ID__c": "2143",'+
        '"LXD_Dato_secreto__c": "asd",'+
        '"LXD_Notas_1__c": null,'+
        '"LXD_Notas_2__c": null,'+
        '"LXD_Contrasena_personal__c": "abc",'+
        '"MailingCountry": "Mexico"'+
        '}');
        RestContext.request = request;    
        Map<String, String> svResult = LXD_RESTClaveOperativaManager.LXD_UpdateClaveOperativa();  // Actualiza el Asset Test
        Map<String,String> expextedResult = new Map<String, String>{
            'Message' => 'Policy not found', 
            'Detail' => 'La combinacion de clave: MN00001 y el pais: Mexico no fue encontrado en la base de datos',
            'Code' => '404'
        };
        System.assertEquals(expextedResult, svResult);
    } 
    
    @isTest static void UpadteShouldReturnResponse400() { //Test exception
        String contactId = createTestRecord();  //crea un object Asset para Test
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Contact/';
        request.httpMethod = 'Post';
        request.requestBody = Blob.valueOf('{'+
        '"LastName": ".",'+
        '"FirstName": "Florencia",'+
        '"MiddleName": null,'+
        '"Suffix": "apellido2",'+
        '"Phone": "54911218029 44",'+
        '"MobilePhone": null,'+
        '"Email": "fviacava@labsxd.com",'+
        '"LXD_Estatus_de_la_clave_operativa__c": "Activo",'+
        '"LXD_Estatus_de_la_relacion__c": "Activo",'+
        '"LXD_Atributos__c": null,'+
        '"LXD_Banderas__c": null,'+
        '"LXD_Genero__c": "Masculino",'+
        '"LXD_Nacionalidad__c": "MEXICANA",'+
        '"LXD_Estado_civil__c": "Soltero",'+
        '"LXD_Tipo_ID__c": "PASAPORTE",'+
        '"LXD_Numero_ID__c": "2143",'+
        '"LXD_Dato_secreto__c": "asd",'+
        '"LXD_Notas_1__c": null,'+
        '"LXD_Notas_2__c": null,'+
        '"LXD_Contrasena_personal__c": "abc",'+
        '"MailingCountry": "Mexico"'+
        '}');

        RestContext.request = request;    
        Map<String, String> svResult = LXD_RESTClaveOperativaManager.LXD_UpdateClaveOperativa();  // Actualiza el Asset Test
        Map<String,String> expextedResult = new Map<String, String>{
            'Message' => 'Bad Request Error', 
            'Code' => '400',
            'Detail' => 'Por favor asegurese de pasar todos los parametros'
        };
        System.assertEquals(expextedResult, svResult);
    } 
    
    // Metodos test del update
    @isTest static void UpadteShouldReturnResponse200AndCreateRelationAccounContact() { //Test positivo
        String contactId = createTestRecord();  //crea un object Asset para Test
        contacto.AccountId = cuentaBase.Id;
        update contacto;
        
        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Contact/';
        request.httpMethod = 'Post';
        request.addHeader('Content-Type', 'application/json');

        RestContext.request = request;
        request.requestBody = Blob.valueOf('{'+
        '"ClaveOperativa": "MN00001",'+
        '"Pais": "Mexico",'+
        '"LastName": ".",'+
        '"FirstName": "Florencia",'+
        '"MiddleName": null,'+
        '"Suffix": "apellido2",'+
        '"Phone": "54911218029 44",'+
        '"MobilePhone": null,'+
        '"Email": "fviacava@labsxd.com",'+
        '"LXD_Clave_operativa__c": "MN00001",'+
        '"LXD_N_Distribuidor__c":"1234",'+
        '"LXD_Estatus_de_la_clave_operativa__c": "Activo",'+
        '"LXD_Estatus_de_la_relacion__c": "Activo",'+
        '"LXD_Atributos__c": null,'+
        '"LXD_Banderas__c": null,'+
        '"LXD_Genero__c": "Masculino",'+
        '"LXD_Nacionalidad__c": "MEXICANA",'+
        '"LXD_Estado_civil__c": "Soltero",'+
        '"LXD_Tipo_ID__c": "PASAPORTE",'+
        '"LXD_Numero_ID__c": "2143",'+
        '"LXD_Dato_secreto__c": "asd",'+
        '"LXD_Notas_1__c": null,'+
        '"LXD_Notas_2__c": null,'+
        '"LXD_Contrasena_personal__c": "abc",'+
        '"MailingCountry": "Mexico"'+
        '}');
        RestContext.request = request;    
        Map<String, String> svResult = LXD_RESTClaveOperativaManager.LXD_UpdateClaveOperativa();  // Actualiza el Asset Test
        Map<String,String> expextedResult = new Map<String, String>{
            'Message' => 'Contact Updated', 
            'Code' => '200'
        };
            
        List<AccountContactRelation> accConRelationList = [
            SELECT Id, AccountId, ContactId, IsActive
                FROM AccountContactRelation 
                WHERE ContactId = :contactId
            		AND AccountId = :cuenta.Id
                    AND IsActive = True
        ];
        System.assertEquals(expextedResult, svResult);
        System.assertEquals(1, accConRelationList.size());
    } 
    // Helper method for create the Contact
    Static Contact contacto;
    Static Account cuentaBase, cuenta;

    static String createTestRecord() {
        cuentaBase = new Account(
        	Name = 'Martin Noy base',
            LXD_N_Distribuidor__c = '12345',
            LXD_Estatus__c = 'Activa'
        );
        insert cuentaBase;
        cuenta = new Account(
        	Name = 'Martin Noy',
            LXD_N_Distribuidor__c = '1234',
            LXD_Estatus__c = 'Activa'
        );
        insert cuenta;
        contacto = new Contact(
            FirstName = 'Martin',
            LastName = 'Noy',
            LXD_Clave_operativa__c = 'MN00001',
            MailingCountry = 'Mexico'
        );
        insert contacto;
        return contacto.Id;
    }       
}