force-app/main/default/objects/Account/fields/LXD_N_Distribuidor__c.field-meta.xml
<CustomField>
    <fullName>LXD_N_Distribuidor__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Número de distribuidor</inlineHelpText>
    <label>Nº Distribuidor</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MX_SKY_ColoiaEnv__c.field-meta.xml
<CustomField>
    <fullName>MX_SKY_ColoiaEnv__c</fullName>
    <label>Colonia</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MX_SKY_EntrecalIeEnvDos__c.field-meta.xml
<CustomField>
    <fullName>MX_SKY_EntrecalIeEnvDos__c</fullName>
    <label>Entre calle 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MX_SKY_EntrecalleUnoEnv__c.field-meta.xml
<CustomField>
    <fullName>MX_SKY_EntrecalleUnoEnv__c</fullName>
    <label>Entre calle 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MX_SKY_NumExtEnv__c.field-meta.xml
<CustomField>
    <fullName>MX_SKY_NumExtEnv__c</fullName>
    <label>Número exterior envío</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MX_SKY_NumIntEnv__c.field-meta.xml
<CustomField>
    <fullName>MX_SKY_NumIntEnv__c</fullName>
    <label>Número interior</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Atributos__c.field-meta.xml
<CustomField>
    <fullName>LXD_Atributos__c</fullName>
    <inlineHelpText>Atributos de la clave operativa</inlineHelpText>
    <label>Atributos</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Banderas__c.field-meta.xml
<CustomField>
    <fullName>LXD_Banderas__c</fullName>
    <inlineHelpText>Programas de capacitación del técnico, vendedor, .....</inlineHelpText>
    <label>Banderas</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Clave_operativa__c.field-meta.xml
<CustomField>
    <fullName>LXD_Clave_operativa__c</fullName>
    <inlineHelpText>Clave operativa</inlineHelpText>
    <label>Clave operativa</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Contrasena_personal__c.field-meta.xml
<CustomField>
    <fullName>LXD_Contrasena_personal__c</fullName>
    <label>Contraseña personal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Dato_secreto__c.field-meta.xml
<CustomField>
    <fullName>LXD_Dato_secreto__c</fullName>
    <inlineHelpText>Dato secreto del Técnico, Vendedor, .....</inlineHelpText>
    <label>Dato secreto</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Estado_civil__c.field-meta.xml
<CustomField>
    <fullName>LXD_Estado_civil__c</fullName>
    <inlineHelpText>Estado civil del Técnico, Vendedor, .....</inlineHelpText>
    <label>Estado civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casado</fullName>
            </value>
            <value>
                <fullName>Soltero</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Estatus_de_la_clave_operativa__c.field-meta.xml
<CustomField>
    <fullName>LXD_Estatus_de_la_clave_operativa__c</fullName>
    <inlineHelpText>Estatus de la clave operativa</inlineHelpText>
    <label>Estatus de la clave operativa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Baja Temporal</fullName>
            </value>
            <value>
                <fullName>Boletinado</fullName>
            </value>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Estatus_de_la_relacion__c.field-meta.xml
<CustomField>
    <fullName>LXD_Estatus_de_la_relacion__c</fullName>
    <inlineHelpText>Estatus de la relación</inlineHelpText>
    <label>Estatus de la relación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Baja logica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Fecha_alta__c.field-meta.xml
<CustomField>
    <fullName>LXD_Fecha_alta__c</fullName>
    <inlineHelpText>Fecha de alta</inlineHelpText>
    <label>Fecha alta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Genero__c.field-meta.xml
<CustomField>
    <fullName>LXD_Genero__c</fullName>
    <inlineHelpText>Género del Técnico, Vendedor, .....</inlineHelpText>
    <label>Genero</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>LXD_Nacionalidad__c</fullName>
    <inlineHelpText>Nacionalidad del Técnico, Vendedor, .....</inlineHelpText>
    <label>Nacionalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COLOMBIANA</fullName>
            </value>
            <value>
                <fullName>COSTARRICENSE</fullName>
            </value>
            <value>
                <fullName>CUBANO</fullName>
            </value>
            <value>
                <fullName>GUATEMALTECA</fullName>
            </value>
            <value>
                <fullName>HONDUREÑA</fullName>
            </value>
            <value>
                <fullName>MEXICANA</fullName>
            </value>
            <value>
                <fullName>NICARAGUENSE</fullName>
            </value>
            <value>
                <fullName>PANAMEÑA</fullName>
            </value>
            <value>
                <fullName>SALVADOREÑA</fullName>
            </value>
            <value>
                <fullName>VENEZOLANA</fullName>
            </value>
            <value>
                <fullName>DOMINICANA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Nivel_de_estudios__c.field-meta.xml
<CustomField>
    <fullName>LXD_Nivel_de_estudios__c</fullName>
    <label>Nivel de estudios</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LXD_Nivel_de_estudios</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Notas_1__c.field-meta.xml
<CustomField>
    <fullName>LXD_Notas_1__c</fullName>
    <inlineHelpText>Notas acerca del Técnico, Vendedor, .....</inlineHelpText>
    <label>Notas 1</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Notas_2__c.field-meta.xml
<CustomField>
    <fullName>LXD_Notas_2__c</fullName>
    <inlineHelpText>Notas acerca del Técnico, Vendedor, .....</inlineHelpText>
    <label>Notas 2</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Numero_ID__c.field-meta.xml
<CustomField>
    <fullName>LXD_Numero_ID__c</fullName>
    <inlineHelpText>Número de identificación del Técnico, Vendedor, ....</inlineHelpText>
    <label>Numero ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Tipo_de_clave_operativa__c.field-meta.xml
<CustomField>
    <fullName>LXD_Tipo_de_clave_operativa__c</fullName>
    <label>Tipo de clave operativa</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LXD_Tipo_de_clave_operativa</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LXD_Tipo_ID__c.field-meta.xml
<CustomField>
    <fullName>LXD_Tipo_ID__c</fullName>
    <inlineHelpText>Tipo de identificación Técnico, Vendedor, .....</inlineHelpText>
    <label>Tipo ID</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credencial para votar (INE)</fullName>
            </value>
            <value>
                <fullName>Licencia para conducir</fullName>
            </value>
            <value>
                <fullName>Pasaporte</fullName>
            </value>
            <value>
                <fullName>Cartilla Militar</fullName>
            </value>
            <value>
                <fullName>Credencial IMSS</fullName>
            </value>
            <value>
                <fullName>Excepción</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MX_SKY_MuniAlca__c.field-meta.xml
<CustomField>
    <fullName>MX_SKY_MuniAlca__c</fullName>
    <label>Municipio / Alcaldia</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LXD_Endpoints__mdt/LXD_Endpoints__mdt.object-meta.xml
<CustomObject>
    <label>Endpoints</label>
    <pluralLabel>Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/LXD_Endpoints__mdt/fields/LXD_accessToken__c.field-meta.xml
<CustomField>
    <fullName>LXD_accessToken__c</fullName>
    <label>AccessToken</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LXD_Endpoints__mdt/fields/LXD_funtion__c.field-meta.xml
<CustomField>
    <fullName>LXD_funtion__c</fullName>
    <label>Funtion</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LXD_Endpoints__mdt/fields/LXD_Url__c.field-meta.xml
<CustomField>
    <fullName>LXD_Url__c</fullName>
    <label>Url</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LXD_Endpoints__mdt/fields/LXD_usuario__c.field-meta.xml
<CustomField>
    <fullName>LXD_usuario__c</fullName>
    <label>Usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LXD_SkyUtils.cls
public without sharing class LXD_SkyUtils {
    public static Boolean checkEnteOperativo(String IdDistribuidor) {
        LXD_Endpoints__mdt WS_CONFIG = LXD_ConfigUtils.getWebServiceConfig('SKY.EnteOperativo');
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(WS_CONFIG.LXD_Url__c+WS_CONFIG.LXD_funtion__c);///InterfaceServices/Salesforce/ConsultarEnteOperativoSapRest
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Authorization','Basic '+EncodingUtil.base64Encode(blob.valueOf(WS_CONFIG.LXD_usuario__c + ':' + WS_CONFIG.LXD_accessToken__c)));
        request.setBody('{'+
            '"cabecera" : {'+
            '"OPERACION" : "ConsultaEnte",'+
            '"APLICATIVO" : "salesforce",'+
            '"PARAMETRO" : [ {'+
                '"NOMBRE" : "",'+
                '"VALOR" : ""'+
            '} ]'+
            '},'+
            '"input" : {'+
            '"DISTRIBUIDOR" : "'+IdDistribuidor+'"'+
            '}'+
        '}'
        );
        try {
            HttpResponse response = http.send(request);
            if(response.getStatusCode() != 200){
                throw new HandledException(response.getBody());
            }
        } catch (Exception e) {
            throw new HandledException(e.getMessage());
        }

        return true;
    }
    public static Boolean AltaClaveOperativa(String IdContacto) {
        LXD_Endpoints__mdt WS_CONFIG = LXD_ConfigUtils.getWebServiceConfig('SKY.AltaClaves');
        Contact contacto = [SELECT 
                LastName,FirstName,MiddleName,Suffix,Phone,MobilePhone,
                Email,LXD_Clave_operativa__c,LXD_Estatus_de_la_clave_operativa__c,
                LXD_Tipo_de_clave_operativa__c,AccountId,Account.LXD_N_Distribuidor__c,MailingPostalCode,
                MailingCity, Title, LXD_Nivel_de_estudios__c, MX_SKY_NumExtEnv__c, MX_SKY_NumIntEnv__c,
                MX_SKY_ColoiaEnv__c, MX_SKY_MuniAlca__c, MX_SKY_EntrecalleUnoEnv__c, MX_SKY_EntrecalIeEnvDos__c,
                LXD_Estatus_de_la_relacion__c,LXD_Atributos__c,LXD_Banderas__c,MailingCountry,
                LXD_Fecha_alta__c,LXD_Genero__c,LXD_Nacionalidad__c,LXD_Estado_civil__c,MailingStreet,MailingState,
                LXD_Tipo_ID__c,LXD_Numero_ID__c,LXD_Dato_secreto__c,LXD_Notas_1__c,
                LXD_Notas_2__c,LXD_Contrasena_personal__c
            FROM Contact
            WHERE Id =: IdContacto
            LIMIT 1
        ];
        system.debug('Contacto = '+ contacto);
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(WS_CONFIG.LXD_Url__c+WS_CONFIG.LXD_funtion__c);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Authorization','Basic '+EncodingUtil.base64Encode(blob.valueOf(WS_CONFIG.LXD_usuario__c + ':' + WS_CONFIG.LXD_accessToken__c)));
        String JSONBody = '{'+ 
            '"Tipos_clave_operativa" : "'+(contacto.LXD_Tipo_de_clave_operativa__c != null ? contacto.LXD_Tipo_de_clave_operativa__c : '')+'",'+
            '"Clave_operativa" : "'+(contacto.LXD_Clave_operativa__c != null ? contacto.LXD_Clave_operativa__c : '')+'",'+
            '"Estatus_Clave" : "'+(contacto.LXD_Estatus_de_la_clave_operativa__c != null ? contacto.LXD_Estatus_de_la_clave_operativa__c : '')+'",'+
            '"Distribuidor_asociado" : "'+(contacto.Account.LXD_N_Distribuidor__c != null ? contacto.Account.LXD_N_Distribuidor__c : '')+'",'+// se debe modificar
            '"Nombre" : "'+(contacto.FirstName != null ? contacto.FirstName : '')+(contacto.MiddleName != null ? ' '+contacto.MiddleName : '')+'",'+
            '"Apellido_Paterno" : "'+(contacto.LastName != null ? contacto.LastName : '')+'",'+
            '"Apellido_Materno" : "'+(contacto.Suffix != null ? contacto.Suffix : '')+'",'+
            '"Pais" : "'+(contacto.MailingCountry != null ? contacto.MailingCountry : '')+'",'+
            '"Calle" : "'+(contacto.MailingStreet != null ? contacto.MailingStreet : '')+'",'+
            '"Numero" : "'+(contacto.MX_SKY_NumIntEnv__c != null ? contacto.MX_SKY_NumIntEnv__c : '')+'",'+
            '"Codigo_postal" : "'+(contacto.MailingPostalCode != null ? contacto.MailingPostalCode : '')+'",'+
            '"Colonia" : "'+(contacto.MX_SKY_ColoiaEnv__c != null ? contacto.MX_SKY_ColoiaEnv__c : '')+'",'+
            '"Delegacion_municipio" : "'+(contacto.MX_SKY_MuniAlca__c != null ? contacto.MX_SKY_MuniAlca__c : '')+'",'+
            '"Ciudad" : "'+(contacto.MailingCity != null ? contacto.MailingCity : '')+'",'+
            '"Estado" : "'+(contacto.MailingState != null ? contacto.MailingState : '')+'",'+
            '"Referencia_calle1" : "'+(contacto.MX_SKY_EntrecalleUnoEnv__c != null ? contacto.MX_SKY_EntrecalleUnoEnv__c : '')+'",'+
            '"Referencia_calle2" : "'+(contacto.MX_SKY_EntrecalIeEnvDos__c != null ? contacto.MX_SKY_EntrecalIeEnvDos__c : '')+'",'+
            '"Telefono" : "'+(contacto.Phone != null ? contacto.Phone : '')+'",'+
            '"Comentarios" : "'+(contacto.LXD_Notas_1__c != null ? contacto.LXD_Notas_1__c : '')+'",'+
            '"Titulo" : "'+(contacto.Title != null ? contacto.Title : '')+'",'+
            '"Email" : "'+(contacto.Email != null ? contacto.Email : '')+'",'+
            '"Nivel" : "'+(contacto.LXD_Nivel_de_estudios__c != null ? contacto.LXD_Nivel_de_estudios__c : '')+'",'+
            '"Responsibilities" : "'+(contacto.LXD_Atributos__c != null ? contacto.LXD_Atributos__c : '')+'",'+
            '"password" : "'+(contacto.LXD_Contrasena_personal__c != null ? contacto.LXD_Contrasena_personal__c : '')+'"'+
        '}';
        system.debug('JSONBody '+JSONBody);
        request.setBody(JSONBody);
        try {
            HttpResponse response = http.send(request);
            if(response.getStatusCode() != 200 && test.isRunningTest()){
                throw new DMLException('No se pudo crear el contacto');
            } else if (response.getStatusCode() != 200) {
            	throw new HandledException(response.getBody());
        	}
        } catch (Exception e) {
            system.debug('Exception = '+ e);
            throw new HandledException(e.getMessage());
        }

        return true;
    }
    @AuraEnabled (cacheable = false)
    public static String getNotasUsuario(String userCode){
        LXD_Endpoints__mdt WS_CONFIG = LXD_ConfigUtils.getWebServiceConfig('SKY.MOODLE');
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(WS_CONFIG.LXD_Url__c+'?wstoken='+WS_CONFIG.LXD_accessToken__c+'&wsfunction='+WS_CONFIG.LXD_funtion__c+'&moodlewsrestformat=json&username='+userCode);
        //http://eusmoodledev.eastus2.cloudapp.azure.com/moodle/webservice/rest/server.php?wstoken=8dc8308c3fa6afaf3b015b07347a73de&wsfunction=local_remote_grades_courses_get_grades_courses_by_username&moodlewsrestformat=json&username=aa68735
        request.setMethod('GET');
        request.setHeader('Content-Type', 'application/json');
        HttpResponse response = http.send(request);
        if(response.getStatusCode() != 200){
            throw new HandledException(response.getBody());
        }
        return response.getBody();
    }
    
    @InvocableMethod(label='Generar Clave Operativa' description='Devuelve un contacto con Clave Operativa' category='Contact')
    public static List<Contact> generarClaveOperativa(List<Id> contactoId){
        
        Decimal clave = 00000;
        String strClave = '';
        String inicialApellido = '';
        List<Contact> contactoConClaveMasAlta;
        List<Contact> contactsResult = new List<Contact>();

        Contact contacto = [
            SELECT Id, LXD_Clave_operativa__c, LastName, Suffix, FirstName 
                FROM Contact 
                WHERE Id = :contactoId[0] 
            LIMIT 1
        ];
        
        if (string.isBlank(contacto.LastName) || contacto.LastName == '.') {
            inicialApellido = contacto.Suffix.toUppercase().left(1);
        }else{
            inicialApellido = contacto.LastName.toUppercase().left(1);
        }
        
        String inicioCO = contacto.FirstName.toUppercase().left(1) + inicialApellido;

        try{
            contactoConClaveMasAlta = [
                SELECT Id, LXD_Clave_operativa__c 
                    FROM Contact
                    WHERE LXD_Clave_operativa__c 
                    LIKE :inicioCO + '%' 
                ORDER BY LXD_Clave_operativa__c DESC 
                LIMIT 1
            ];
            
            if (!contactoConClaveMasAlta.isEmpty()) {
                clave = Decimal.valueOf(contactoConClaveMasAlta[0].LXD_Clave_operativa__c.substring(2,7));
            }            

        } catch (Exception e){
            system.debug('Exception '+ e);
        }

        strClave = String.valueOf(clave+1).leftPad(5, '0');
        contacto.LXD_Clave_operativa__c = inicioCO + strClave;
        update contacto;
        contactsResult.add(contacto);
        return contactsResult;
    }
    public static Integer getRandomElement(Integer ListSice){
        Double randomNumber = Math.random(); 
        Integer randomIndex = (randomNumber *(ListSice-1)).intValue(); 
        return randomIndex;
    }
}