force-app/main/default/objects/LXD_Endpoints__mdt/LXD_Endpoints__mdt.object-meta.xml
<CustomObject>
    <label>Endpoints</label>
    <pluralLabel>Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/LXD_Endpoints__mdt/fields/LXD_accessToken__c.field-meta.xml
<CustomField>
    <fullName>LXD_accessToken__c</fullName>
    <label>AccessToken</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LXD_Endpoints__mdt/fields/LXD_funtion__c.field-meta.xml
<CustomField>
    <fullName>LXD_funtion__c</fullName>
    <label>Funtion</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LXD_Endpoints__mdt/fields/LXD_IsProduction__c.field-meta.xml
<CustomField>
    <fullName>LXD_IsProduction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsProduction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LXD_Endpoints__mdt/fields/LXD_Url__c.field-meta.xml
<CustomField>
    <fullName>LXD_Url__c</fullName>
    <label>Url</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LXD_Endpoints__mdt/fields/LXD_usuario__c.field-meta.xml
<CustomField>
    <fullName>LXD_usuario__c</fullName>
    <label>Usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LXD_ConfigUtils.cls
public with sharing class LXD_ConfigUtils {
    private static Organization currentOrg;

	public static Boolean isProductionEnviroment() {

		if (currentOrg == null) {
			currentOrg = [SELECT Id, Name, IsSandbox FROM Organization LIMIT 1];
		}

		return !currentOrg.isSandbox;
	}

	public static LXD_Endpoints__mdt getWebServiceConfig(String wsName) {
		return [
			SELECT
				DeveloperName,
				LXD_Url__c,
				LXD_accessToken__c,
				LXD_usuario__c,
                LXD_funtion__c,
				LXD_IsProduction__c
			FROM LXD_Endpoints__mdt
			WHERE LXD_IsProduction__c = :isProductionEnviroment()
				AND MasterLabel = :wsName
			LIMIT 1
		];
	}
}